/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class SolutionTest {
    @Test
    void searchTest() {
        Solution solution = new Solution();
        int[] nums = new int[] { -1, 0, 3, 5, 9, 12 };
        int target = 9;
        int answer = 4;
        int output = solution.search(nums, target);
        String message = String.format("search(%s,%d) should return '%d'", Arrays.toString(nums), target, answer);
        assertEquals(answer, output, message);
        nums = new int[] { -1, 0, 3, 5, 9, 12 };
        target = 2;
        answer = -1;
        message = String.format("search(%s,%d) should return '%d'", Arrays.toString(nums), target, answer);
        assertEquals(answer, solution.search(nums, target), message);
        return;
    }

}
