/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package binarysearch;


public class Solution {
    public int search(int[] nums, int target) {
        int n = nums.length;
        int a = 0;
        int b = n - 1;
        while (b-a > 1) {
            if (nums[a + (b - a) / 2] < target) {
                a += (b - a) / 2;
            } else {
                b -= (b - a) / 2;
            }
        }
        if (nums[a] == target) {
            return a;
        } else if (nums[b]==target) {
            return b;
        }
        else {
            return -1;
        }
    }
}
